@startuml pizza

class PizzaStore{
    orderPizza()
}

class SimplePizzaFactory{
    createPizza()
}

class Pizza{
    prepare()
    bake()
    cut()
    box()
}

class CheesePizza{
}
class VeggiePizza{

}
class ClamPizza{
}

class PepperoniPizza{}

Pizza <|-- CheesePizza
Pizza <|-- VeggiePizza
Pizza <|-- ClamPizza
Pizza <|-- PepperoniPizza


@enduml